# This workflow will install Python and run the app.py

name: Python application

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install requests
    - name: Run app.py
      run: python app.py
    - name: Commit files
      run: |
        git config --local user.email "sven.brieden@gmail.com"
        git config --local user.name "Sven Brieden"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
