# This workflow will install Python and run the app.py

name: Python application

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 7-21 * * *'
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install requests
    - name: Run app.py
      run: python app.py
    - name: Write File
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: written_by_action.md
        contents: |
          echo "Hello World!"
        write-mode: append
